### ISSUE TITLE
Feature Request: Maintain Tours, assign one or multiple to a user

### ISSUE THREAD

**Issue by MaTTaDox** [Malsch-Solutions/vecodesk-issues#23]
For a better overview, it would be nice to maintain tours in VeCoDesk. So that a drive can filter for his tour before his tour to check if there are any problems with his vending machines.

Tour settings view:
- tour name
- user selection
- sortable list of customer addresses, contains a sortable list of the selected devices
- add button where you can search for devices

```[tasklist]
### Tasks
- [ ] https://github.com/Malsch-Solutions/vecodesk-issues/issues/30
- [ ] https://github.com/Malsch-Solutions/vecodesk-issues/issues/29
- [ ] https://github.com/Malsch-Solutions/vecodesk-issues/issues/28
- [ ] https://github.com/Malsch-Solutions/vecodesk-issues/issues/27
```
