### ISSUE TITLE
support ticket subject: optional selection

### ISSUE THREAD

**Issue by MaTTaDox** [Malsch-Solutions/vecodesk-issues#3]
**Is your feature request related to a problem? Please describe.**
To make input easier for the user, the user should be able to select the subject from a list and not write it by himself.

**Describe the solution you'd like**
Add an optional setting to the backend which adds different subjects based on the device type and a description template.

```[tasklist]
### Tasks
- [ ] https://github.com/Malsch-Solutions/vecodesk-issues/issues/16
- [ ] https://github.com/Malsch-Solutions/vecodesk-issues/issues/17
- [ ] https://github.com/Malsch-Solutions/vecodesk-issues/issues/18
- [ ] https://github.com/Malsch-Solutions/vecodesk-issues/issues/19
```

**Comment by MaTTaDox** [comment]
Will be included in the next release
